apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myapp-deployment
  label:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: dep-app
template:
  metadata:
    labels:
      app:dep-app
  spec:
    containers:
     - name: nginx
       image: nginx